### ISSUE TITLE
Set up Supabase Auth

### ISSUE THREAD

**Issue by kiwicopple** [supabase/next-server-components#1]
# Chore

We need a couple of things for auth:

### Set up a login/register component

@MildTomato how soon do you think the component will be ready? If it's >2 days we can just custom code this or use [thor's](https://github.com/thorwebdev/nextjs-subscription-payments/blob/main/pages/signin.js) code

### Cookies

@thorwebdev is this one good to go? https://github.com/supabase/gotrue-js/pull/33

We'll need serverside validation for this one: https://github.com/supabase/next-server-components/blob/master/libs/session.js

https://github.com/supabase/next-server-components/blob/244e5e7c0f4aafdf0304d552e763fe6496b37bf7/pages/api/notes/index.js#L6

**Comment by MildTomato** [comment]
I think the auth component might be working by tomorrow.

Best to custom code it if you don't want to wait, I can come in and update it with `ui` after if you like.

**Comment by kiwicopple** [comment]
I'll wait! Not enough time to code things twice ..

**Comment by MildTomato** [comment]
@supabase/ui 0.2.0 released with auth.

example from `@supabas/ui` storybook stories of it in use
```javascript

import { Auth } from '@supabase/ui'

const supabase = createClient(
  '<url>',
  '<key>'
)

const Container = (props) => {
  const { user } = Auth.useUser()
  if (user)
    return (
      <>
        <Typography.Text>Signed in: {user.email}</Typography.Text>
        <Button block onClick={() => props.supabaseClient.auth.signOut()}>
          Sign out
        </Button>
      </>
    )
  return props.children
}

export const Default = (args) => (
  <Auth.UserContextProvider {...args}>
    <Container {...args}>
      <Auth {...args} />
    </Container>
  </Auth.UserContextProvider>
)

Default.args = {
  supabaseClient: supabase
}
```
